{{- if .Values.web.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-web
  minReplicas: {{ .Values.web.hpa.minReplicas }}
  maxReplicas: {{ .Values.web.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.web.hpa.cpuUtil }}
{{- end }}
---
{{- if and .Values.worker.enabled .Values.worker.hpa .Values.worker.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-worker
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-worker
  minReplicas: {{ .Values.worker.hpa.minReplicas }}
  maxReplicas: {{ .Values.worker.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.worker.hpa.cpuUtil }}
{{- end }}
