apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pg-migrations
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: fpt-ddi
    app.kubernetes.io/instance: {{ .Release.Name }}
binaryData: {}
data:
{{ (.Files.Glob "migrations/*.sql").AsConfig | indent 2 }}
