{{- if .Values.envSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envSecret.name | default "ddi-prod-env" }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: fpt-ddi
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
{{- range $k, $v := .Values.envSecret.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
